### PR TITLE
Use macros to fix stack overflow when deriving for local classes

### LINKED ISSUE #2263: `StackOverflowError` if local class since 0.14.7 with Scala 3
build.sbt

```scala
libraryDependencies += "io.circe" %% "circe-generic" % "0.14.7"

scalaVersion := "3.3.3"

run / fork := true
```

Main.scala

```scala
package example

import io.circe.Decoder
import io.circe.Json
import io.circe.generic.semiauto._
import io.circe.syntax._

object Main {
  def main(args: Array[String]): Unit = {
    case class A(x: Int)
    object A {
      implicit val decoder: Decoder[A] = deriveDecoder[A]
    }

    println(Json.obj("x" -> Json.fromInt(3)).as[A])
  }
}
```

`sbt run` result

```
[info] running (fork) example.Main 
[error] Exception in thread "main" java.lang.StackOverflowError
[error] 	at example.Main$.example$Main$$$_$A$2(Main.scala:11)
[error] 	at example.Main$A$3$.<init>(Main.scala:12)
[error] 	at example.Main$.A$lzyINIT1$1(Main.scala:11)
[error] 	at example.Main$.example$Main$$$_$A$2(Main.scala:11)
[error] 	at example.Main$A$3$.<init>(Main.scala:12)
[error] 	at example.Main$.A$lzyINIT1$1(Main.scala:11)
[error] 	at example.Main$.example$Main$$$_$A$2(Main.scala:11)
[error] 	at example.Main$A$3$.<init>(Main.scala:12)
[error] 	at example.Main$.A$lzyINIT1$1(Main.scala:11)
[error] 	at example.Main$.example$Main$$$_$A$2(Main.scala:11)
[error] 	at example.Main$A$3$.<init>(Main.scala:12)
[error] 	at example.Main$.A$lzyINIT1$1(Main.scala:11)
[error] 	at example.Main$.example$Main$$$_$A$2(Main.scala:11)
[error] 	at example.Main$A$3$.<init>(Main.scala:12)
[error] 	at example.Main$.A$lzyINIT1$1(Main.scala:11)
[error] 	at example.Main$.example$Main$$$_$A$2(Main.scala:11)
```

### PR DESCRIPTION
**Pull request by mrdziuban**
Fixes #2263 
Supersedes and closes #2278 if merged

@hamnis this is an alternate approach to what I did in #2278. By using macros for derivation we can match on the `Mirror` and extract the `MirroredLabel`, `MirroredElemLabels`, and `MirroredElemTypes` types without causing a stack overflow.

There are two caveats (the tests will fail if either of these things change in the future):

1. Any methods that call the macros must mark their `Mirror.Of` as `inline`
2. Any parameters derived from the `Mirror` in the macro must be passed by-name, e.g. `fromProduct` in `ConfiguredDecoder.ofProduct` and `ConfiguredEncoder.ofSum`

### CODE REVIEW

**Review by hamnis — DISMISSED** [review]
I found this easier to understand

**Comment by hamnis** [comment]
Letting @zarthross decide to merge

File: modules/core/shared/src/main/scala-3/io/circe/derivation/ConfiguredCodec.scala [hunk 1]
```diff
@@ -17,47 +17,97 @@
...
 
 import scala.deriving.Mirror
-import scala.compiletime.constValue
+import scala.compiletime.{ constValue, summonInline }
+import scala.quoted.*
 import io.circe.{ Codec, Decoder, Encoder, HCursor, JsonObject }
 
 trait ConfiguredCodec[A] extends Codec.AsObject[A], ConfiguredDecoder[A], ConfiguredEncoder[A]
 object ConfiguredCodec:
-  private def of[A](nme: String, decoders: => List[Decoder[?]], encoders: => List[Encoder[?]], labels: List[String])(
```
Comment (zarthross) [inline modules/core/shared/src/main/scala-3/io/circe/derivation/ConfiguredCodec.scala:25]: I would love to be shown wrong on this, but removing this method concerns me.

I know that when you use inline on a private method, (the original `derived` below calls this of), that there is a public accessor created, in this case it should be `inner$of`.

If we have some library, lets call if `A` that used theses macros, and some end user app called `B`.  
What happens if circe is updated to `ofProduct`, built a built with `of`... and `B` updates the version of circe to no longer include `inner#of`?  I feel like we will get a NoSuchMethodError in application `B`?

I'm worried we'll have a similar problem to https://github.com/circe/circe/issues/2089

Comment (zarthross) [reply modules/core/shared/src/main/scala-3/io/circe/derivation/ConfiguredCodec.scala:25]: Not sure why mima doesn't catch this situation....

Comment (mrdziuban) [reply modules/core/shared/src/main/scala-3/io/circe/derivation/ConfiguredCodec.scala:25]: Wow I didn't know about that behavior but you're definitely right, I confirmed in a fresh project. I'll put the `of` methods back

Comment (mrdziuban) [reply modules/core/shared/src/main/scala-3/io/circe/derivation/ConfiguredCodec.scala:25]: Oh wait actually, just putting `of` back doesn't fix the issue. The `inline$of` method only exists in the bytecode if `of` is called from an `inline` method, so we could also need to add a dummy `inline` method that still calls it. Given that, what do you think the best course of action is @zarthross?

Comment (zarthross) [reply modules/core/shared/src/main/scala-3/io/circe/derivation/ConfiguredCodec.scala:25]: Yeah, this is certainly an awkward part of scala3 inlines... we could try adding a private method with the name `inline$of`?  I'm not sure if scala 3 will allow that, or we could try a dummy inline method as you suggested... we'll just have to try a few things and check the generated bytecode....

Comment (mrdziuban) [reply modules/core/shared/src/main/scala-3/io/circe/derivation/ConfiguredCodec.scala:25]: I ended up adding `inline$of` methods. They can't be `private` otherwise they cause a `java.lang.IllegalAccessError` instead of a binary incompatibility, but I made them `private[derivation]` and marked them as `deprecated`

**Review by zarthross — APPROVED** [review]
Thanks for the hard work on this!
